"use strict"

module.exports.ERR_STRING_EXPECTED = "ERR_STRING_EXPECTED"
module.exports.ERR_HANDLER_EXPECTED = "ERR_HANDLER_EXPECTED"
module.exports.CONSTRUCTOR_NATIVE_ERR = `class constructor can't be a native object`
module.exports.TODO = "ERR_NOT_DEFINED__TODO"
module.exports.NO_CLASS_DESCRIPTOR_ERR = `failed to acquire object`
module.exports.ROUTE_BUSY_ERR = "ROUTE_BUSY_ERR"
module.exports.UNSPECIFIED_EVENT_TYPE_ERR = "UNSPECIFIED_EVENT_TYPE_ERR"
module.exports.UNSPECIFIED_EVENT_ERR = "UNSPECIFIED_EVENT_ERR"
module.exports.UNSPECIFIED_MODEL_KEY_ERR = "UNSPECIFIED_MODEL_KEY_ERR"
module.exports.UNSPECIFIED_PATH_ERR = "UNSPECIFIED_PATH_ERR"
module.exports.UNSPECIFIED_ROUTE_PATH_ERR = "UNSPECIFIED_ROUTE_PATH_ERR"
module.exports.WARN_UNSAFE_TPL = "UNSAFE_TPL_VARS"
module.exports.WARN_LATE_NEXT = "LATE_NEXT"
